### ISSUE TITLE
No es posible añadir libpkcs11-fnmtdnie

### ISSUE THREAD

**Issue by juanjosepablos** [alfem/FireFirma#1]
Debian 8.
libpkcs11-fnmtdnie 1.4.1

En opciones > Privacidad &Seguridad > Certificados > Dispositivos de seguridad
Cargar y al añadir /usr/lib/libpkcs11-fnmtdnie.so 
Da un error no es posible añadir el modulo.

**Comment by juanjosepablos** [comment]
Ubuntu 16.0.7 
libpkcs11-fnmtdnie 1.6.1
Si funciona correctamente.

**Comment by alfem** [comment]
Al ser un Appimage, los binarios y librerías están aislados de los del sistema y se regeneran cada vez que lanzas el ejecutable. Probablemente sea por eso.
