### ISSUE TITLE
indica que hay una versión nueva del aplicativo y falla

### ISSUE THREAD

**Issue by UserPanic** [alfem/FireFirma#5]
salta un aviso de que hay una actualización del aplicativo, como se actualizaría para que no saltase

**Comment by alfem** [comment]
Lo he probado y no falla. Sí que avisa de que hay una nueva versión de AutoFirma, pero si esperas un segundo o dos, puedes elegir el fichero y firmarlo.

En cualquier caso, me lo apunto para actualizarlo (si alguien quiere probar, hay instrucciones en #2) cuando tenga tiempo.

**Comment by UserPanic** [comment]
He visto las instrucciones pero no me queda claro del todo, puedes especificarlo más para poder aplicarlo?

**Comment by alfem** [comment]
Dime donde te atascas y te echo una mano.

**Comment by UserPanic** [comment]
He seguido el proceso que indicas, pero me falla al compilarlo me dice Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project afirma-signature-retriever: Compilation failure: Compilation failure: a partir de ahí, ya me da al traste

**Comment by UserPanic** [comment]
todo el texto de error que me indica al final del proceso al hacer el mvn install [INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestSignatureValidation.testCadesLTAValidation:42 » FileNotFound C:\Users\carlos.gamuci\Desktop\salida/cades-lta-cosign.csig (No existe el archivo o el directorio)
[INFO] 
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] afirma-client 1.8.2 ................................ SUCCESS [  1.180 s]
[INFO] afirma-core 1.8.2 .................................. SUCCESS [ 11.721 s]
[INFO] afirma-core-keystores 1.8.2 ........................ SUCCESS [  4.797 s]
[INFO] afirma-crypto-batch-client 1.8.2 ................... SUCCESS [  2.795 s]
[INFO] afirma-crypto-cadestri-client 1.8.2 ................ SUCCESS [  2.754 s]
[INFO] afirma-crypto-core-pkcs7 1.8.2 ..................... SUCCESS [  2.831 s]
[INFO] afirma-crypto-core-pkcs7-tsp 1.8.2 ................. SUCCESS [  3.058 s]
[INFO] afirma-crypto-cades 1.8.2 .......................... SUCCESS [  5.660 s]
[INFO] afirma-crypto-cades-multi 1.8.2 .................... SUCCESS [ 13.313 s]
[INFO] afirma-crypto-cms 1.8.2 ............................ SUCCESS [  4.499 s]
[INFO] afirma-crypto-core-xml 1.8.2 ....................... SUCCESS [  2.389 s]
[INFO] afirma-crypto-odf 1.8.2 ............................ SUCCESS [  9.003 s]
[INFO] afirma-crypto-pdf-common 1.8.2 ..................... SUCCESS [  1.917 s]
[INFO] afirma-crypto-padestri 1.8.2 ....................... SUCCESS [  5.371 s]
[INFO] afirma-crypto-pdf 1.8.2 ............................ SUCCESS [ 26.921 s]
[INFO] afirma-crypto-xades 1.8.2 .......................... SUCCESS [ 29.106 s]
[INFO] afirma-crypto-xmlsignature 1.8.2 ................... SUCCESS [ 14.801 s]
[INFO] afirma-crypto-ooxml 1.8.2 .......................... SUCCESS [ 15.465 s]
[INFO] afirma-crypto-validation 1.8.2 ..................... FAILURE [  8.601 s]
[INFO] afirma-crypto-xadestri-client 1.8.2 ................ SKIPPED
[INFO] afirma-keystores-filters 1.8.2 ..................... SKIPPED
[INFO] afirma-keystores-mozilla 1.8.2 ..................... SKIPPED
[INFO] afirma-ui-core-jse 1.8.2 ........................... SKIPPED
[INFO] afirma-ui-core-jse-keystores 1.8.2 ................. SKIPPED
[INFO] afirma-core-massive 1.8.2 .......................... SKIPPED
[INFO] afirma-server-triphase-signer-cache 1.8.2 .......... SKIPPED
[INFO] afirma-server-triphase-signer-core 1.8.2 ........... SKIPPED
[INFO] afirma-server-triphase-signer-document 1.8.2 ....... SKIPPED
[INFO] afirma-ui-simpleafirma-plugins 1.8.2 ............... SKIPPED
[INFO] afirma-ui-simpleafirma-plugins-manager 1.8.2 ....... SKIPPED
[INFO] afirma-ui-simpleafirma-plugin-hash 1.0 ............. SKIPPED
[INFO] afirma-ui-simpleafirma-plugin-validatecerts 1.0 .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:46 min
[INFO] Finished at: 2023-06-21T10:05:30+02:00
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project afirma-crypto-validation: 
[ERROR] 
[ERROR] Please refer to /home/userkiller/Escritorio/clienteafirma/afirma-crypto-validation/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :afirma-crypto-validation

**Comment by alfem** [comment]
Prueba a compilar saltando los tests:

mvn clean install -DskipTests -Denv=install

**Comment by alfem** [comment]
Y de todas formas, lo de compilar AutoFirma no siempre es necesario. Con la 1.6 sí, porque hay que retocar alguna ruta, pero con la última versión que probé no hacía falta.

**Comment by alfem** [comment]
Ayer tenía (por fin!) un rato libre:

https://github.com/alfem/FireFirma/releases/tag/3.0

**Comment by UserPanic** [comment]
aún poniendo mvn clean install -DskipTests -Denv=install me sigue apareciendo el mismo error...
