### ISSUE TITLE
No me funciona :(

### ISSUE THREAD

**Issue by viogp** [alfem/FireFirma#6]
Hola,

Lo primero, muchísimas gracias por este paquete.

Llevo un día entero mirando cosas y cambiando y probando, pero no he conseguido firmar el documento que me hace falta. Al correr con FireFirma-3.0 obtengo el siguiente error:

-----------------------------

Errores:

[Ha solicitado la cancelación del proceso de firma. Histórico de intentos: -P_AD_ES_BASIC_SHA_256_WITH_RSA vía AUTOFIRMA_MINIAPPLET: Error FIR_037: No se ha podido completar el proceso de firma mediante AutoFirma. Para verificar la compatibilidad de su navegador realice un proceso de firma completo en: https://valide.redsara.es/valide/firmar/ejecutar.html. Si el error persiste, inténtelo en otro navegador. [Ref. 20231213201014559] Petición: f68c1d24-f083-42a0-b218-95ad8bfc9d7f]
------------------------

Mi certificado está vigente según FNMT, pero valide.redsara.es no me lo admite. Así que sospecho que el problema viene de ahí, pero no sé cómo solucionarlo (que no sea pedir un certificado nuevo para una máquina de Windows).

Mi máquina: Ubuntu 22.04.3 LTS
y entiendo que FireFirma controla la versión de Firefox, java y Autofirma.

**Comment by alfem** [comment]
Ese mensaje de error es raro. Normalmente Autofirma da erorres que empiezan por "SAF_", pero ese  "FIR_037" me suena a antiguo.

¿Podrías probar en https://valide.redsara.es/valide/firmar/ejecutar.html y comprobar si da el mismo error u otro código?

Ayuda a diagnosticar el problema que lances FireFirma desde un terminal de Ubuntu y trates de firmar. En el terminal saldrá bastante información que siempre da pistas.

También puedes intentar usar una versión anterior de Firefirma (https://github.com/alfem/FireFirma/releases/tag/1.4), por si la web donde tratas de firmar está desactualizada.

**Comment by viogp** [comment]
¡Muchas gracias por tu pronta respuesta!

FireFirma1.4 me da problemas con Firefox: no me deja abrir las webs.

En cuanto al error en valide:
* En la web de valide me aparece "Error al firmar      No se pudo contactar con AutoFirma"
* En la terminal, lo último que me sale es: [Fatal Error] :1:1: Content is not allowed in prolog. 
* Antes del mensaje de error, hay toda una serie de letras y números, entiendo que con la manipulación de la GUI , y justo antes: INFO: Mostramos pantalla principal
Dec 14, 2023 9:49:08 AM es.gob.afirma.standalone.SimpleAfirma loadDefaultKeyStore
INFO: Se omite la carga concurrente de almacen por haberse hecho una precarga previa
Dec 14, 2023 9:49:29 AM es.gob.afirma.standalone.ui.pdf.SignPdfDialog positionSelected
INFO: Propiedades establecidas mediante GUI: {layer2Text=Firmado por


En los mensajes de error que aparecen por la terminal me aparecen estos "warnings" que puede que sean relevantes:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by es.gob.afirma.standalone.SimpleAfirma (file:/usr/lib/AutoFirma/AutoFirma.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of es.gob.afirma.standalone.SimpleAfirma
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by alfem** [comment]
Necesitaría toda la salida del terminal. Con los trozos sueltos que has puesto no es posible hacer un diagnóstico.

**Comment by viogp** [comment]
Gracias por tu tiempo, envío la salida completa de uno de los intentos.
[out3.txt](https://github.com/alfem/FireFirma/files/13685866/out3.txt)

**Comment by alfem** [comment]
Creo que el problema es este:
```

INFO: Se toma como perfil activo de Mozilla el indicado en el 'profiles.ini' v2 o sup.
Dec 14, 2023 3:12:21 PM es.gob.afirma.keystores.mozilla.NSPreferences getFireFoxUserProfileDirectory
INFO: Se utilizara el perfil activo de Mozilla: 'USERHOME/snap/firefox/common/.mozilla/firefox/ctj4aiee.default-release

```
¿Por casualidad tienes otro Firefox abierto al mismo tiempo que FireFirma?

**Comment by viogp** [comment]
Con tu comentario y hablando con un compañero sobre copiar el certificado en otra máquina de linux he conseguido firmar desde una máquina virtual de linux!!! 

El problema está en mi instalación de Firefox. No lo tenía abierto, al correr FireFirma, pero estaba interfiriendo de algún modo que no ye llegado a entender.

Muchas gracias.

**Comment by alfem** [comment]
Estupendo! Cierro el ticket entonces.
